# Generated by Django 4.0.3 on 2022-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='api_hash',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='api_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
